# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
