# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='moderator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
