# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 20, 17, 13, 51, 415077, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
